services:
  copilot-api:
    image: ghcr.io/yidasanqian/ghcopilot2api:latest
    container_name: ghcopilot2api
    #command: ["--verbose"] # Enable verbose logging for debugging
    ports:
      - "127.0.0.1:4141:4141"
    env_file:
      - ./.env
    environment:
      GH_TOKEN: ${GH_TOKEN:-}
      LOG_FILE: /var/log/copilot-api/copilot-api.log
    volumes:
      - ./copilot-data:/root/.local/share/copilot-api
      - ./logs:/var/log/copilot-api
    restart: unless-stopped
